/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_eoe_jni_Bridge */

#ifndef _Included_cn_eoe_jni_Bridge
#define _Included_cn_eoe_jni_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_eoe_jni_Bridge
 * Method:    startListen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_eoe_jni_Bridge_startListen
  (JNIEnv *, jclass);

/*
 * Class:     cn_eoe_jni_Bridge
 * Method:    addImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_eoe_jni_Bridge_addImage
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
